services:
  heracless:
    container_name: heracless-development-container
    build:
      context: .   # The directory with the Podmanfile
      dockerfile: ./container_files/PythonPodmanfile   # Path to the Podmanfile (or Dockerfile)
    volumes:
      - ../heracless:/workspace/ # Correct path to your project
    command: ["sh", "-c", "pip install -e /workspace/ && exec bash"]  # Adjust the entry point of your app
    stdin_open: true
    tty: true  # Needed for interactive containers
  jobshoplab:
    container_name: jobshoplab-development-container
    build:
      context: .   # The directory with the Podmanfile
      dockerfile: ./container_files/PythonPodmanfile   # Path to the Podmanfile (or Dockerfile)
    volumes:
      - ../jobshoplab:/workspace/ # Correct path to your project
    command: ["sh", "-c", "pip install -e /workspace/[dev] && exec bash"]  # Adjust the entry point of your app
    stdin_open: true
    tty: true  # Needed for interactive containers
  opti_pipe:
    container_name: opti_pipe-development-container
    build:
      context: .   # The directory with the Podmanfile
      dockerfile: ./container_files/PythonPodmanfile   # Path to the Podmanfile (or Dockerfile)
    volumes:
      - ../opti_pipe:/workspace/ # Correct path to your project
    command: ["sh", "-c", "exec bash"]  # Adjust the entry point of your app
    stdin_open: true
    tty: true  # Needed for interactive containers
